a,b=input().split()
a=int(a)
b=int(b)

print(1) if a>=b else print(0)
print(1) if a>b else print(0)
print(1) if b>=a else print(0)
print(1) if b>a else print(0)
print(1) if a==b else print(0)
print(1) if a!=b else print(0)